### ISSUE TITLE
Check SIMD feature set at runtime

### ISSUE THREAD

**Issue by ozgrakkurt** [DoumanAsh/xxhash-rust#26]
Hey!

This would be nice since it is not always possible to use `target-cpu=native` because build may be done on one machine and then deployed to another. Does this make sense to implement?

**Comment by DoumanAsh** [comment]
You can add particular feature also via `target-cpu` e.g. `+avx`
I didn't really bother to implement it because right now there are only two SIMD implementations that I took from original C code.
SSE2(always enabled for x86_64)
AVX2(which is not always desirable due to how expensive it is)

Maybe if  NEON becomes fully stable I could add runtime detection, but most of the time you should be aware of target feature set ahead of itme

**Comment by ozgrakkurt** [comment]
oh makes sense if it is enabled by default, I though it was using avx2/neon. thanks for the explanation

**Comment by DoumanAsh** [comment]
This is only the case for SSE2 because it is available on all x86_64 or at least all for the last twenty years.
But if you can, feel free to make PR to add runtime detection
