### ISSUE TITLE
Hash{Map, Set} types with xxhash as default hasher?

### ISSUE THREAD

**Issue by YurySolovyov** [DoumanAsh/xxhash-rust#30]
it would be nice to have convenience types like e.g. [FxHash](https://docs.rs/fxhash/0.2.1/fxhash/type.FxHashMap.html) does

basically:
```rust
use std::collections::HashMap;
use xxhash_rust::xxh64::Xxh64Builder;

pub type XHashMap<K, V> = HashMap<K, V, Xxh64Builder>;

fn main() {
    let mut map = XHashMap::default();

    map.insert("foo", 1);
    map.insert("bar", 2);

    println!("Map -> {:?}", map);
}
```

**Comment by DoumanAsh** [comment]
xxh3 already has [builder](https://docs.rs/xxhash-rust/0.8.7/xxhash_rust/xxh3/struct.Xxh3Builder.html)
I did not implement builder for other variants due to xxh3 not having enough output and xxh64 being strictly inferior to xxh3_64 variant

I do not think it is necessary to add type alias for hash map because it is not really up to this crate to decide how you plan to use hasher.
In proper code base you would either have your own aliases or you declare hasher as part of your own struct making alias redundant

**Comment by YurySolovyov** [comment]
Understandable.
