### ISSUE TITLE
How it compares to rustc's hash function

### ISSUE THREAD

**Issue by yyy33** [DoumanAsh/xxhash-rust#38]
The rust compiler has an fxhash, which seems to be unencrypted as well, how does the speed of xxhash compare to its

**Comment by DoumanAsh** [comment]
Generally Rust's hash interface is not very good for performance of xxhash due to it re-creating state every time.
But on large input (i.e. 1kb) it would generally out perform fxhash.

If you're only concerned with usage within hash map I believe default hasher would suit you more than enough as most of the time your input will be fairly small keys.

But if you need high performance outside hash map I recommend  to not use default hasher for sure.
Especially if you need handle fairly large inputs (e.g. file, other binary blobs)

Other notes to consider:
- Most efficient way to hash is using oneshot functions: [xxh3_128](https://docs.rs/xxhash-rust/0.8.10/xxhash_rust/xxh3/fn.xxh3_128.html) and [xxh3_64](https://docs.rs/xxhash-rust/0.8.10/xxhash_rust/xxh3/fn.xxh3_64.html)
- If you need streaming variant then prefer to [reset](https://docs.rs/xxhash-rust/0.8.10/xxhash_rust/xxh3/struct.Xxh3.html#method.reset) rather than creating new hasher every time

Do note that if you need uniquness prefer hashes that has at least 128 bytes output like xxh3

**Comment by DoumanAsh** [comment]
btw I believe default hasher is SipHasher13 for HashMap
